include: package:lints/recommended.yaml

linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - require_trailing_commas