version: '3.1'
services:
  strom_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strom_api
    environment: 
      - TZ=Europe/Madrid #do NOT change
      - PRICE_LOG_LEVEL=info
      - HTTP_LOG_LEVEL=info
      - HTTP_PORT=3001
      - RATING_MARGIN=10
      - PROTECTED_MODE=false
      - RAPID_API_SECRET=
    restart:
      always
      delay: 1m
    ports: 
      - "3001:3001"    
    logging:
      driver: "json-file"
      options:
        max-size: 100m