version: '3.1'
services:
  pvpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvpc_server
    environment: 
      - TZ=Europe/Madrid    
      - LOG_LEVEL=info
    restart: always
    ports: 
      - "3009:3000"    
    logging:
      driver: "json-file"
      options:
        max-size: 100m