version: '3.1'
services:
  strom_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strom_api
    env-file: 
    - .env
    restart: always
    ports: 
      - "3001:3001"    
    logging:
      driver: "json-file"
      options:
        max-size: 100m