name: strom_api
description: RESTful server for electricity prices. 
version: 1.0.0
repository: https://github.com/willyfromtheblock/strom_api

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

dependencies:
  alfred: ^1.1.0+1
  collection: ^1.17.1
  cron: ^0.5.1
  dio: ^5.0.1
  dio_smart_retry: ^6.0.0
  logger: ^2.0.2
  timezone: ^0.9.1
