name: pvpc_server
description: RESTful server for Spanish electricity prices. 
version: 1.0.0
repository: https://github.com/willyfromtheblock/pvpc_server

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  alfred: ^1.1.0+1
  collection: ^1.17.1
  cron: ^0.5.1
  dio: ^5.0.1
  dio_smart_retry: ^5.0.0
  logger: ^1.2.2
  timezone: ^0.9.1
